[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
dockerContext = "."

[deploy]
startCommand = "node scripts/wait-for-db.js && npm run migrate && npm run seed && PORT=${PORT:-4000} npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
